INSERT INTO client (id, version, firstname, lastname) VALUES (1, 1, 'Olivier', 'Martin');
INSERT INTO client (id, version, firstname, lastname) VALUES (2, 1, 'Olivier', 'Dubois');
INSERT INTO client (id, version, firstname, lastname) VALUES (3, 1, 'Dubois', 'Albatros');
INSERT INTO client (id, version, firstname, lastname) VALUES (4, 1, 'Dutronc', 'Burkitos');
INSERT INTO client (id, version, firstname, lastname) VALUES (5, 1, 'Duschmol', 'Lola');
INSERT INTO client (id, version, firstname, lastname) VALUES (6, 1, 'Pipo', 'Monsieur');
INSERT INTO client (id, version, firstname, lastname) VALUES (7, 1, 'Xavier', 'De La Duschmolerie');
INSERT INTO client (id, version, firstname, lastname) VALUES (8, 1, 'Bidule', 'De la renaudiere');
INSERT INTO client (id, version, firstname, lastname) VALUES (9, 1, 'Gauthier', 'Pompidout');
INSERT INTO client (id, version, firstname, lastname) VALUES (10, 1, 'Lara', 'Kroft');
INSERT INTO client (id, version, firstname, lastname) VALUES (11, 1, 'Lucie', 'Inglund');