# Read Me First
:toc:
:toclevels: 7
:sectnums:
:sectnumlevels: 7

:revnumber: {project-version}

The samples here demonstrate REST pagination (and a little sorting)

Main approaches for pagination:

* pagination data in the response body (similar to Spring)
* pagination data in the header
** RFC 5988: Link header
** RFC 2616: Content Range, Accept Range
** Custom (i.e. see Heroku for instance)
* Use Open API 3.0 Links

Also, we need to be able to handle the following kind of pagination:

* with total page count (i.e. Page support from Spring Data) +
  for classic pagination
* with next/previous  (i.e. Slice support from Spring Data) +
  for paging across large results (db performance)

|===
| Approach | Classic pagination support | Next/Previous support | Comments

| Spring Data REST
| Y
| limited
| Only talking about out of the box pagination - slice support is limited in the way that it relied on a page number, not a generic pagination key

| RFC 5988
| Y
| N
|

| RFC 2616
| Y
| Y
a| Implies more work on the frontend to implement classic pagination support.
Perhaps we should give a try at Spring OOB support for this RFC in spring hateoas ?

| Open API Links
| ?
| ?
| Didn't look at it

|===


## Pagination in Spring Data REST

Note: Paging and Sorting is demonstrated using the Repository, but you can implement your own controller
and service layer and still use Pageable/Page and Slice objects).
 
### demo-rest-pagination (Page support)

Demonstrates Spring Data REST pagination and sorting capacities.

This sample uses an embedded database

* start the app
* http://localhost:8080/clients?size=5&page=0&sort=firstname,desc&sort=lastname,asc
  you'll see something like
```
{
  "_embedded" : {
    "clients" : [ {
      "firstname" : "Xavier",
      "lastname" : "De La Duschmolerie",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/clients/7"
        },
        "client" : {
          "href" : "http://localhost:8080/clients/7"
        }
      }
    }, {
      "firstname" : "Pipo",
      "lastname" : "Monsieur",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/clients/6"
        },
        "client" : {
          "href" : "http://localhost:8080/clients/6"
        }
      }
    }, {
      "firstname" : "Olivier",
      "lastname" : "Dubois",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/clients/2"
        },
        "client" : {
          "href" : "http://localhost:8080/clients/2"
        }
      }
    }, {
      "firstname" : "Olivier",
      "lastname" : "Martin",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/clients/1"
        },
        "client" : {
          "href" : "http://localhost:8080/clients/1"
        }
      }
    }, {
      "firstname" : "Lucie",
      "lastname" : "Inglund",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/clients/11"
        },
        "client" : {
          "href" : "http://localhost:8080/clients/11"
        }
      }
    } ]
  },
  "_links" : {
    "first" : {
      "href" : "http://localhost:8080/clients?page=0&size=5&sort=firstname,desc&sort=lastname,asc"
    },
    "self" : {
      "href" : "http://localhost:8080/clients"
    },
    "next" : {
      "href" : "http://localhost:8080/clients?page=1&size=5&sort=firstname,desc&sort=lastname,asc"
    },
    "last" : {
      "href" : "http://localhost:8080/clients?page=2&size=5&sort=firstname,desc&sort=lastname,asc"
    },
    "profile" : {
      "href" : "http://localhost:8080/profile/clients"
    }
  },
  "page" : {
    "size" : 5,
    "totalElements" : 11,
    "totalPages" : 3,
    "number" : 0
  }
}
```


### demo-rest-pagination (Slice support)

atm, when I'm returning Slice from my Repository I'm still getting the totalElements and totalPages
in my REST response (surely because Spring must return the sample implementation class).


## Code first approach (a-la-Spring)

See subproject openapi-pagination

With this approach we try to achieve the same json for pagination as the one sued by oob Spring Data REST, 
but with an API-first design approach (writing the Open API 3.0 specification and generating Controller code from that)

See client-api.yml

This one contains 2 variants:

* client1: 
** request: page, size, sort as query parameters using Open API primitive types
** response: uses a generic Paging type that can be reused across all of our paginated APIs.
* client2: only the request changes  
** request uses a generic type with style: form, this enables us to reuse the query params across all of our paginated
   APIs too. Note: remaining glitch is that sort query params are converter to a single String element containing
   all sort param values concatenated with ',' (i.e. http://localhost:8080/clients2?size=10&sort=toto&page=1&sort=tata
   -> I have sort=toto,tata on the server side)   


## API Design First approach (RFC 2616: Content-Range header)

See client 3 in client-api.yml

This sample demonstrate using the following approach for the pagination:

* for the request: range query parameter (type String, with a value <start-index>-<last-index>) 
* for the response: Accept-Range and Content-Range response header

Implementation is not ready yet, but is straightforward.

Pros:

* Pagination is not intrusive in the response body

Cons:

* Some proxies filter out the range headers (rfc2616 only standardises bytes unit and some proxies drop the header
when they don't understand it).
  See Section 3.1 of RFC 7233: "A proxy MAY discard a Range header field that contains a range unit it does not understand."
* A little more work parsing the header response


## API Design First approach (RFC 5988: Link header)

Spring hateoas provides first class support for that.

Sample:

```
GET /gists/starred
Status: 200 OK
Link: <https://api.github.com/resource?page=2>; rel="next",
      <https://api.github.com/resource?page=5>; rel="last"
```

Github implements this kind of pagination.

Strangely on some ressource it also embeds pagination data in the response body
see https://api.github.com/search/repositories?q=tetris+language:assembly&sort=stars&order=desc&page=1&per_page=10

Pros:

* This approach provides a way to do slice pagination (if you don't provide a last element).
* This approach is not intrusive in the response body.

Cons:

* more efforts on the client-side:
  you'll need to parse the 'last' Link value to be able to build a pagination component (giving direct
  access to a given page) - and hope you can rely on the page parameter being consistent.
  See for instance https://developer.github.com/v3/guides/traversing-with-pagination/


## References

* https://github.com/interagent/http-api-design/issues/36
  and https://devcenter.heroku.com/articles/platform-api-reference#ranges
* https://www.transposit.com/blog/2019.12.10-using-extensions-to-support-pagination-in-openapi/
* Support of RFC 5988 in Spring Hateoas: https://github.com/spring-projects/spring-hateoas/issues/710
* https://developer.github.com/v3/guides/traversing-with-pagination/
* https://developer.github.com/v3/#pagination
* https://docs.spring.io/spring-data/rest/docs/current/reference/html/#paging-and-sorting
* https://www.baeldung.com/rest-api-pagination-in-spring
